# https://golangci-lint.run/usage/configuration/#config-file
linters:
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused

linters-settings:
  depguard:
    list-type: "allowlist"
    include-go-root: false
    packages:
      - "github.com/magefile/mage/sh"
      - "github.com/charmbracelet/log"
      - "github.com/declaredata/fuse_go/gen"
